### ISSUE TITLE
BGP show outputs not updated.

### ISSUE THREAD

**Issue by mairp** [srl-labs/srl-sros-telemetry-lab#1]
BGP show outputs not updated.

**Comment by hellt** [comment]
@mairklone thanks
will you raise a Pull Request with a fix?

**Comment by mairp** [comment]
> @hellt, now is attached in the comment.


[README.md](https://github.com/srl-labs/srl-sros-telemetry-lab/files/9893357/README.md)

**Comment by hellt** [comment]
Closed via #2
