### ISSUE TITLE
Adding a new gnmi subscription not in Prometheus 

### ISSUE THREAD

**Issue by danield71** [srl-labs/srl-sros-telemetry-lab#14]
I did an addition of a subscription (SROS path state/system/version) in the gnmi yml.
Redeployed the lab, in one the the dcgw router, show system telemetry grpc subscription command is showing a new sub for this path.

in Prometheus, the metric is not in the targets.it is because the router did not send this subscription data ?
Using gnmi cli, I’m able to receive the data for this path.

can we add a new subscription into the lab ? 

my goal is to add a new sub in order to add it to the Grafana dashboard.

**Comment by hellt** [comment]
Hi
this is because the version value is of `string` type and prometheus metrics are floats only.
There is still a way to store the version information in prometheus by promoting this value to the measurement's tag value.

I remember @KTodts did something like that

**Comment by danield71** [comment]
Thanks Roman
I will find another sub with float values
Regards
