### ISSUE TITLE
Password for grafana/Prometheus?

### ISSUE THREAD

**Issue by hellt** [srl-labs/srl-sros-telemetry-lab#9]
It has been reported that people see login screens for grafana in particular. 
@mairp can you check if you saved passwords accidentally? If so, can you add the credentials or remove them from grafana?

**Comment by mairp** [comment]
I have saved the passwords only on my web browser, to me it should  not be saved in the dashboard configuration, but not sure,  if login screen needs to be remove we should include a configuration setting the "Anonymous Authentication" https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/grafana/#anonymous-authentication
Inside of the container, if it so? I can give a shot.

**Comment by hellt** [comment]
When I do public dashboards I don't set a password at all. Given poeple report seeing password screen indicate the password has been set apparently. 
https://discord.com/channels/860500297297821756/865574858385784842/1086602138894995546

This is from containerlab discord

**Comment by mairp** [comment]
all right, yes indeed this login screen is set by default in the grafana.ini file for built-in user authentication, I was able to disable it overwriting the default grafana.ini 
https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/#grafana-auth
I will submit a PR with a config that hide the login form.

**Comment by hellt** [comment]
closed via #10
